# Setup
title: mlon
# tagline: 'making lots of noise'
description: ''
url: http://mlon.com
baseurl: ''
paginate: 2
permalink: /:slug:output_ext

# About/contact
author:
  name: Adrien Friggeri
  url: https://mlon.com/
  email: adrien@mlon.com

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-youtube

# Optimize Jekyll
exclude:
  - .devcontainer
  - .editorconfig
  - .frontmatter
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .vscode
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: :compressed

# Custom vars
# google_analytics_id: #UA-XXXX-Y
